baseURL = "https://materialescolaryoficina.tole.es"
title = "Últimas ofertas"
theme = "portfolio"
languageCode = "es-es"
# Enable comments by entering your Disqus shortname
disqusShortname = ""


[sitemap]
  changefreq = "hourly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Nuestras últimas ofertas"
  copyright = ""
  sidebarAbout = []
  # Enable Google Analytics by entering your tracking code
  gtag = "G-CCLRP3R12J"
  yandex = "27d3b6cce1d74b40"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Raíz  "
  url = "/"
  home = true


  [outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
